det_model: 
  name: efficientdet-d8
  # pretrained: results/effdet-train/efficientdet-d8_SAM.log
  pretrained: null
  finetune: 
    do: false
    step1_epochs: 5
    step2_epochs: 5
uid: efficientdet-d8_multi5_flip

inference:
  inference_only: true
  multiscale_test:
    sizes:
      - [384, 256]   # 3:2
      - [768, 512]   # 6:4
      - [1152, 768]  # 9:6
      - [1536, 1024] # 12:8
      - [1920, 1280] # 15:10
  flip_test:
    horizontal: true

result_dir: results/effdet-train
data_dir: data/ori

batch_size: 1
num_cpus: 3
start_epoch: 1
final_epoch: 200
SAM: false
padding: 20
fold: 1
earlystop_patience: 10

debug: false

seed: 20210309

crop:
  - 192
  - 28
  - 1728
  - 1052
input_width: 1536 #768 #1536
input_height: 1024 #512 #1024

lr: 0.000001
scheduler:
  type: CosineAnnealingWarmUpRestarts
  params:
    T_0: 10
    T_mult: 1
    eta_max: 0.001
    T_up: 5
    gamma: 0.5
  # type: CosineAnnealingWarmRestarts
  # params:
  #   T_0: 10
  #   T_mult: 1
  #   eta_min: 0.00001
  #   verbose: false
  # type: ReduceLROnPlateau
  # params:
  #   factor: 0.5
  #   patience: 3
  #   verbose: true
