det_model: efficientdet-d4
uid: efficientdet-d4
result_dir: results/effdet-train
data_dir: data/ori

lr: 0.0001
batch_size: 5
num_cpus: 5
start_epoch: 1
final_epoch: 200
SAM: false
padding: 20
fold: 1

debug: false

seed: 20210309
inference: false

input_width: 1024
input_height: 512
