# TODO: BCE loss로 학습도 해보고싶은데

uid: HRNet_W48_null
seed: 20210309
result_dir: results/hrnet-train/example

pose_model:
  name: HRNet-W48
  pretrained: results/hrnet-train/ckpt-HRNet_W48_SAM_1.pth

dataset:
  dir: results/effdet-train/example/efficientdet-d7_multi5_flip_median_test_imgs
  normalize: true
  batch_size: 1
  num_workers: 1

test:
  multiscale_test:
    input_sizes: 
      # - [288, 384]
      # - [576, 768]
      - [864, 1152]
    rotations: 
      - 0
      # - 1
      # - 3
    horizontal_flip:
      # - false
      - true
    voting_method: key-median # mean, median, key-mean, key-median
