pose_model: HRNet-W48
uid: HRNet_W48-SAM-BCE
result_dir: results/hrnet-train2
data_dir: data/ori
debug: false
seed: 20210309

train:
  max_epochs: 200
  SAM: true
  folds: 
    - 1
    - 2
    - 3
    - 4
    - 5
  checkpoints: 
    - null
    - null
    - null
    - null
    - null
  loss_type: awing # ce, bce, mse, mae, awing
  
  lr: 0.00001
  scheduler:
    type: CosineAnnealingWarmUpRestarts
    params:
      first_cycle_steps: 10
      cycle_mult: 1.0
      max_lr: 0.005
      min_lr: 0.0001
      warmup_steps: 2
      gamma: 0.8
    # type: CosineAnnealingWarmRestarts
    # params:
    #   T_0: 10
    #   T_mult: 1
    #   eta_min: 0.00001
    #   verbose: false
    # type: ReduceLROnPlateau
    # params:
    #   factor: 0.5
    #   patience: 3
    #   verbose: true
  
dataset:
  train_dir: data/ori/train_imgs
  target_file: data/ori/train_df.csv
  
  normalize: false
  
  batch_size: 10
  num_cpus: 10
  padding: 20
  input_width: 576
  input_height: 768

