pose_model: HRNet-W48
result_dir: results/hrnet-train
data_dir: data/ori

lr: 0.0001
batch_size: 10
start_epoch: 1
SAM: false
folds: [1,2,3,4,5]
checkpoints: [null,null,null,null,null]
padding: 20
add_joint_loss: false

debug: false
step1_epoch: 5
step2_epoch: 10
step3_epoch: 100

input_width: 576
input_height: 768

uid: HRNet_W48
seed: 20210309
