pose_model: HRNet-W48
uid: HRNet_W48_SAM
result_dir: results/hrnet-train
data_dir: data/ori

lr: 0.0001
batch_size: 10
num_cpus: 10
start_epoch: 1
SAM: true
folds: 
  - 3
checkpoints: 
  - null
padding: 20
add_joint_loss: false

debug: false
step1_epoch: 10
step2_epoch: 15
step3_epoch: 200

input_width: 576
input_height: 768

seed: 20210309
inference: false
